import { useState } from 'react';
import { FileText, Printer, X } from 'lucide-react';
import { SecondaryButton } from './ui';

// A mocked submission dossier (eCTD Module 2) — the tangible output of the Submission Dossier Pod.
// Synthetic content, consistent with the run. Draft only: not for filing until signed off.

function Cite({ id }: { id: string }) {
  return <sup className="ml-0.5 font-mono text-[9px] font-semibold text-[var(--info)]">[{id}]</sup>;
}

function Page({ children, n, total }: { children: React.ReactNode; n: number; total: number }) {
  return (
    <div className="dossier-page relative mx-auto mb-6 w-full max-w-[820px] bg-white px-16 py-14 text-[#2a2a2a] shadow-lg">
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden"
      >
        <span className="rotate-[-30deg] text-[120px] font-bold tracking-widest text-[#000]/[0.04]">DRAFT</span>
      </div>
      <div className="mb-8 flex items-center justify-between border-b border-[#e2dcd6] pb-2 text-[10px] uppercase tracking-wider text-[#8a8a8a]">
        <span>NWP-2894512 · Submission Dossier</span>
        <span>Module 2 · CTD</span>
      </div>
      <div className="relative min-h-[760px]">{children}</div>
      <div className="mt-8 flex items-center justify-between border-t border-[#e2dcd6] pt-2 text-[10px] text-[#8a8a8a]">
        <span>DRAFT — not for filing · generated by Submission Dossier Pod v1.3</span>
        <span>
          Page {n} of {total}
        </span>
      </div>
    </div>
  );
}

function DossierModal({ onClose }: { onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-black/60" role="dialog" aria-modal="true">
      <style>{`@media print { body > #root { visibility: hidden; } .dossier-doc, .dossier-doc * { visibility: visible; } .dossier-doc { position: absolute; inset: 0; overflow: visible; background: #fff; } .dossier-page { box-shadow: none !important; page-break-after: always; } .dossier-noprint { display: none !important; } }`}</style>
      <div className="dossier-noprint flex items-center justify-between border-b border-white/10 px-4 py-3 text-white">
        <div className="flex items-center gap-2 text-sm font-medium">
          <FileText className="h-4 w-4" /> Dossier draft · NWP-2894512 · Module 2
          <span className="rounded bg-white/15 px-1.5 py-0.5 text-[11px]">DRAFT · not signed</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => window.print()}
            className="flex items-center gap-1.5 rounded-lg bg-white/10 px-3 py-1.5 text-sm font-medium text-white hover:bg-white/20"
          >
            <Printer className="h-4 w-4" /> Save as PDF
          </button>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className="grid h-8 w-8 place-items-center rounded-lg bg-white/10 text-white hover:bg-white/20"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      </div>
      <div className="dossier-doc flex-1 overflow-y-auto p-6" onClick={(e) => e.target === e.currentTarget && onClose()}>
        {/* Cover */}
        <Page n={1} total={3}>
          <div className="flex h-[760px] flex-col items-center justify-center text-center">
            <div className="text-xs uppercase tracking-[0.3em] text-[#8a8a8a]">Common Technical Document</div>
            <h1 className="mt-4 text-4xl font-bold tracking-tight">Submission Dossier</h1>
            <div className="mt-2 text-lg text-[#5b5b5b]">Module 2 · Clinical Overview &amp; Summaries</div>
            <div className="mt-10 space-y-1">
              <div className="text-xl font-semibold">NWP-2894512</div>
              <div className="text-[#5b5b5b]">Adjuvanted adult vaccine booster</div>
              <div className="text-[#5b5b5b]">Northwind Vaccines · FDA (US)</div>
            </div>
            <div className="mt-12 rounded-lg border border-[#e2dcd6] bg-[#faf8f6] px-5 py-3 text-sm text-[#5b5b5b]">
              Draft v0.9 · Phase III complete, database locked · every claim cited
              <div className="mt-1 font-semibold text-[#b7791f]">Not for filing — pending departmental sign-off</div>
            </div>
          </div>
        </Page>

        {/* 2.5 Clinical Overview */}
        <Page n={2} total={3}>
          <div className="mb-6 text-[11px] uppercase tracking-wider text-[#8a8a8a]">Table of contents</div>
          <ol className="mb-10 space-y-1 text-sm">
            <li className="flex justify-between border-b border-dashed border-[#e2dcd6] pb-1">
              <span>2.5 Clinical Overview</span>
              <span className="text-[#8a8a8a]">3</span>
            </li>
            <li className="flex justify-between border-b border-dashed border-[#e2dcd6] pb-1">
              <span>2.7.3 Summary of Clinical Efficacy</span>
              <span className="text-[#8a8a8a]">3</span>
            </li>
            <li className="flex justify-between border-b border-dashed border-[#e2dcd6] pb-1">
              <span>Appendix A · Health-authority question responses</span>
              <span className="text-[#8a8a8a]">3</span>
            </li>
          </ol>
          <h2 className="text-lg font-bold">2.5 Clinical Overview</h2>
          <p className="mt-3 text-[15px] leading-relaxed">
            The clinical development programme for NWP-2894512 comprised three pivotal Phase III trials (NWV-301,
            NWV-302 and NWV-305) enrolling 14,210 participants.
            <Cite id="C1" /> The primary efficacy endpoint was met in all three trials, with a pooled vaccine efficacy of
            91.3% (95% CI 86.9–94.4) in the per-protocol population.
            <Cite id="C2" /> No new safety signal was observed relative to the Phase II profile; reactogenicity was
            transient and predominantly mild to moderate.
            <Cite id="C2" />
          </p>
          <p className="mt-3 text-[15px] leading-relaxed text-[#5b5b5b]">
            The benefit–risk assessment supports registration in the proposed adult booster indication. Each efficacy
            figure in this overview traces to a locked endpoint row; no interim readout was used.
          </p>
        </Page>

        {/* 2.7.3 efficacy + appendix */}
        <Page n={3} total={3}>
          <h2 className="text-lg font-bold">2.7.3 Summary of Clinical Efficacy</h2>
          <table className="mt-3 w-full border-collapse text-sm">
            <thead>
              <tr className="border-b-2 border-[#2a2a2a] text-left">
                <th className="py-1.5 pr-2 font-semibold">Trial</th>
                <th className="py-1.5 pr-2 font-semibold">Phase</th>
                <th className="py-1.5 pr-2 font-semibold">N</th>
                <th className="py-1.5 pr-2 font-semibold">Primary endpoint</th>
                <th className="py-1.5 font-semibold">Efficacy</th>
              </tr>
            </thead>
            <tbody>
              {[
                ['NWV-301', 'III', '5,120', 'Met', '90.8%'],
                ['NWV-302', 'III', '4,690', 'Met', '92.1%'],
                ['NWV-305', 'III', '4,400', 'Met', '91.0%'],
              ].map((row) => (
                <tr key={row[0]} className="border-b border-[#e2dcd6]">
                  {row.map((c, i) => (
                    <td key={i} className={i === 0 ? 'py-1.5 pr-2 font-medium' : 'py-1.5 pr-2 text-[#5b5b5b]'}>
                      {c}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
          <p className="mt-2 text-xs text-[#8a8a8a]">
            Pooled per-protocol efficacy 91.3% (95% CI 86.9–94.4).
            <Cite id="C2" />
          </p>

          <h2 className="mt-10 text-lg font-bold">Appendix A · Health-authority question responses</h2>
          <div className="mt-3 space-y-4 text-[15px] leading-relaxed">
            <div>
              <div className="font-semibold">Q1. Provide lot-to-lot immunogenicity bridging.</div>
              <p className="text-[#5b5b5b]">
                First-pass response drafted from the approved 2019 adjuvanted-zoster submission answer, found by HAQ&amp;R
                and reused verbatim where applicable.
                <Cite id="C3" /> <span className="font-medium text-[#b7791f]">Flag: confirm it still applies to this lot.</span>
              </p>
            </div>
            <div>
              <div className="font-semibold">Q2. Justify the proposed dosing interval in the label.</div>
              <p className="text-[#5b5b5b]">
                Drafted from the pivotal-trial schedule.
                <Cite id="C5" /> <span className="font-medium text-[#b7791f]">Flag: one dose-interval term differs from the approved USPI — pending labelling sign-off.</span>
              </p>
            </div>
          </div>
        </Page>
      </div>
    </div>
  );
}

export function DossierButton() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <SecondaryButton onClick={() => setOpen(true)}>
        <FileText className="h-4 w-4" /> Open dossier draft
      </SecondaryButton>
      {open && <DossierModal onClose={() => setOpen(false)} />}
    </>
  );
}
